# Post
###
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Title",
    "content": "Content",
    "sender_id": "1"
}
###
GET http://localhost:3000/post
###
GET http://localhost:3000/post?sender=1
###
GET http://localhost:3000/post/6741a07761c9d48c34165a0d
###
PUT http://localhost:3000/post/6741a07761c9d48c34165a0d
Content-Type: application/json

{
    "title": "Updated title",
    "content": "Updated content",
    "sender_id": "1"
}

# Comment
###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "message": "hi this is a message 2",
    "sender_id": "1",
    "post_id": "67474a3d2651e79673ab702f"
}
###
GET http://localhost:3000/comment
###
GET http://localhost:3000/comment?postId=67474a3d2651e79673ab702f
###
GET http://localhost:3000/comment/6778f7f548cb7802a935f9a4 
###
PUT http://localhost:3000/comment/677937f96a58d21af8a2827e 
Content-Type: application/json

{
    "message33444": "updated messageeeeeee",
    "sender_id": "2",
    "post_id": "67474a3d2651e79673ab702f"
}
###
DELETE http://localhost:3000/comment/6778f7f548cb7802a935f9a4   


# User
###
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "ido3@gmai.com",
    "password": "123",
    "firstName": "ido",
    "lastName": "winkler"
}

### delete user
DELETE http://localhost:3000/user/67794da8e94a5a981864b52b    

### get user by id
GET http://localhost:3000/user/6779363fb2dcaebe0376ffa5  


### delete non existing user
DELETE http://localhost:3000/user/67474a3d2651e79673ab702f

### invalid email
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "ido.com",
    "password": "123",
    "firstName": "ido",
    "lastName": "winkler"
}

### update user info
PUT http://localhost:3000/user/6779363fb2dcaebe0376ffa5
Content-Type: application/json

{
    "email": "ido3@gmai.com",
    "firstName": "idoooooo",
    "lastName": "winkler"
}

