# Post
###
POST http://localhost:3000/post
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2E5MWZhZDQ4MjI3N2VlMTI0YTA1ZiIsInRpbWVzdGFtcCI6MTczNjA4NjAxOTAxOSwiaWF0IjoxNzM2MDg2MDE5LCJleHAiOjE3MzYzNDUyMTl9.Uj7guwwRgFi_CyNzqNegFsoElP8I49D3GrwMaRl5heQ

{
    "title": "Title",
    "content": "Content",
}
###
GET http://localhost:3000/post
###
GET http://localhost:3000/post?sender=1
###
GET http://localhost:3000/post/677a96853685998bbc58b16c
###
PUT http://localhost:3000/post/677a9bdde5974f7c3500aa0c 
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2E5MWZhZDQ4MjI3N2VlMTI0YTA1ZiIsInRpbWVzdGFtcCI6MTczNjA4NjAxOTAxOSwiaWF0IjoxNzM2MDg2MDE5LCJleHAiOjE3MzYzNDUyMTl9.Uj7guwwRgFi_CyNzqNegFsoElP8I49D3GrwMaRl5heQ

{
    "title": "Updated title222",
    "content": "Updated content",
}

###
DELETE http://localhost:3000/post/677a9cf258c8b91eb69a4213 
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2E5YzYyMjExZTE3YTE1YmFlNjM5YyIsInRpbWVzdGFtcCI6MTczNjA4ODY4ODI4OSwiaWF0IjoxNzM2MDg4Njg4LCJleHAiOjE3MzYzNDc4ODh9.HNPky1BRl-gE7pbpiNoyp--9kGceRstUUwQYF1isPt0

# Comment
###
POST http://localhost:3000/comment
Content-Type: application/json

{
    "message": "hi this is a message 2",
    "post_id": "67474a3d2651e79673ab702f"
}
###
GET http://localhost:3000/comment
###
GET http://localhost:3000/comment?postId=67474a3d2651e79673ab702f
###
GET http://localhost:3000/comment/6778f7f548cb7802a935f9a4 
###
PUT http://localhost:3000/comment/677937f96a58d21af8a2827e 
Content-Type: application/json

{
    "message33444": "updated messageeeeeee",
    "post_id": "67474a3d2651e79673ab702f"
}
###
DELETE http://localhost:3000/comment/6778f7f548cb7802a935f9a4   


# User
###
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "ido3@gmai.com",
    "password": "123",
    "firstName": "ido",
    "lastName": "winkler",
    "userName": "ido"
}

### delete user
DELETE http://localhost:3000/user  

### get user by id
GET http://localhost:3000/user/6779363fb2dcaebe0376ffa5  

### invalid email
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "ido.com",
    "password": "123",
    "firstName": "ido",
    "lastName": "winkler",
    "userName": "ido"
}

### update user info
PUT http://localhost:3000/user
Content-Type: application/json

{
    "firstName": "idoooooo",
    "lastName": "winkler"
}

###

# Auth
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "id02@gmail.com",
    "password": "123",
    "firstName": "ido",
    "lastName": "fdsd",
    "userName": "lfdsfdsior"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "id02@gmail.com",
    "password": "123"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzkxYzMyZWQ1MGVlYjViNTY5NTViNiIsInRpbWVzdGFtcCI6MTczNTk5MjgwMzUzOCwiaWF0IjoxNzM1OTkyODAzLCJleHAiOjE3MzY1OTc2MDN9.W2Muku7STPVMbIvytjhrV5jWTvHU_5XtobYnl2wOaxQ"
}

###
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzkxYzMyZWQ1MGVlYjViNTY5NTViNiIsInRpbWVzdGFtcCI6MTczNTk5MjgwMzUzOCwiaWF0IjoxNzM1OTkyODAzLCJleHAiOjE3MzY1OTc2MDN9.W2Muku7STPVMbIvytjhrV5jWTvHU_5XtobYnl2wOaxQ"
}
